//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentFeedData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public int CompanyID { get; set; }
        public string PropertyAddress1 { get; set; }
        public string PropertyAddress2 { get; set; }
        public string PropertyCity { get; set; }
        public string PropertyState { get; set; }
        public string PropertyZip { get; set; }
        public string PropertyEmail { get; set; }
        public string PropertyPhone { get; set; }
        public int Threshold { get; set; }
        public decimal LateFee { get; set; }
        public int LateFeeApplied { get; set; }
        public int EvictionThreshold { get; set; }
        public int SMSThreshold { get; set; }
        public int BankFee { get; set; }
        public decimal DailyLateFee { get; set; }
        public decimal PetFine { get; set; }
        public decimal DailyPetFine { get; set; }
        public int Gas { get; set; }
        public int Electricity { get; set; }
        public int Water { get; set; }
        public int Trash { get; set; }
        public int TV { get; set; }
        public int Internet { get; set; }
        public decimal LaborRate { get; set; }
        public decimal EvictionFee { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal NRSecurityDeposit { get; set; }
        public decimal MaxLateFee { get; set; }
        public decimal MinBalance { get; set; }
        public decimal ApplicationFee { get; set; }
        public decimal AdminFee { get; set; }
        public Nullable<int> Active { get; set; }
        public string PropertyEIN { get; set; }
        public string PropertyURL { get; set; }
        public string PropertyWebsite { get; set; }
        public string PropertyLongDescription { get; set; }
        public Nullable<int> PropertyOfficeHoursID { get; set; }
    }
}
