//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentFeedData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unittype
    {
        public int UnitTypeID { get; set; }
        public string UnitType1 { get; set; }
        public string UnitTypeDescription { get; set; }
        public int PropertyID { get; set; }
        public decimal UnitCharge { get; set; }
        public decimal ApplicationFee { get; set; }
        public decimal AdminFee { get; set; }
        public Nullable<int> IsFurnished { get; set; }
        public Nullable<int> IsSmokingAllowed { get; set; }
        public Nullable<int> IsWheelChairAccessible { get; set; }
        public Nullable<int> PetsAllowed { get; set; }
        public Nullable<int> MaxAllowedPeople { get; set; }
        public string LeaseDurationMonth { get; set; }
        public string ParkingType { get; set; }
        public string LaundryType { get; set; }
        public string SquareFootage { get; set; }
        public int UnitResidenceTypeID { get; set; }
        public string TotalBedrooms { get; set; }
        public string TotalBathrooms { get; set; }
    }
}
