//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRentFeedData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit
    {
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public int PropertyID { get; set; }
        public int UnitTypeID { get; set; }
        public int Occupied { get; set; }
        public System.DateTime VacantDate { get; set; }
        public string Comment { get; set; }
    }
}
